---
experiment:
  name: mine/utzappos
dataset:
  data_dir: ut-zap50k
  dataset: utzappos
  splitname: compositional-split-natural
model_params:
  model: compcos
  dropout: true
  norm: true
  nlayers: 2
  relu: false
  fc_emb: 768,1024
  emb_dim: 300
  emb_init: glove
  image_extractor: resnet18
  train_only: true
  static_inp: false
training:
  batch_size: 128
  load:
  lr: 5.0e-05
  lrg: 0.001
  margin: 1.0
  cosine_scale_components: 10
  max_epochs: 300
  norm_family: imagenet
  save_every: 10000
  test_batch_size: 64
  test_set: val
  topk: 1
  wd: 5.0e-05
  workers: 8
  update_features: false
  freeze_features: false
  epoch_max_margin: 100
  C_y: MLP
  residual: False
  attr_objs_fc_emb: 2048,2048
  IC: True
  eta: 1.1
